name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or 'master' if that's your default branch

permissions:
  contents: write  # required for pushing to gh-pages
  pages: write     # required to deploy to Pages
  id-token: write  # required by deploy-pages action

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # This should point to your `index.html` location

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
